"""add stripe_payment_intent_id to orders

Revision ID: 4f8e496777c0
Revises: 08ef7b1c3c9f
Create Date: 2026-08-14 17:07:05.487713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f8e496777c0'
down_revision: Union[str, Sequence[str], None] = '08ef7b1c3c9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
