"""add stripe_payment_intent_id to orders

Revision ID: 673a67da9aec
Revises: 1a8896d630ac
Create Date: 2026-08-14 18:57:34.519700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '673a67da9aec'
down_revision: Union[str, Sequence[str], None] = '1a8896d630ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'payment_status',
               existing_type=mysql.ENUM('PENDING', 'APPROVED', 'FAILED'),
               type_=sa.Enum('PENDING', 'APPROVED', 'FAILED', 'CANCELED', name='paymentstatus'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'payment_status',
               existing_type=sa.Enum('PENDING', 'APPROVED', 'FAILED', 'CANCELED', name='paymentstatus'),
               type_=mysql.ENUM('PENDING', 'APPROVED', 'FAILED'),
               existing_nullable=False)
    # ### end Alembic commands ###
