"""add stripe_payment_intent_id to orders

Revision ID: 8634bb28b84c
Revises: 673a67da9aec
Create Date: 2026-08-14 19:27:01.397746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8634bb28b84c'
down_revision: Union[str, Sequence[str], None] = '673a67da9aec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
