"""add stripe_payment_intent_id to orders

Revision ID: e4c4839d6b6f
Revises: 6f0426a1bf5b
Create Date: 2026-08-13 13:38:11.041332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4c4839d6b6f'
down_revision: Union[str, Sequence[str], None] = '6f0426a1bf5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('stripe_payment_intent_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'stripe_payment_intent_id')
    # ### end Alembic commands ###
